import { ChevronDown, Menu } from 'lucide-react';
import { useState } from 'react';
import headerLogo from '../../Group 3320.svg';

const baseUrl = (path = '') => `${import.meta.env.BASE_URL?.replace(/\/$/, '') || ''}/${path}`;

export function UnifiedHeader() {
  const [open, setOpen] = useState(false);
  const links = [['Главная', baseUrl()], ['Грузоперевозки', baseUrl('road-freight-russia')], ['Мультимодальные', baseUrl('multimodal-container')], ['Все решения', baseUrl('#solutions')], ['Сервисы', baseUrl('#services')]];
  return <header className="unified-header sticky top-0 z-50 bg-[#440D84] text-white shadow-[0_8px_30px_rgba(36,8,67,0.15)]"><div className="mx-auto flex h-[52px] max-w-[1440px] items-center justify-between px-6 sm:px-8 lg:px-10"><a href={baseUrl()} aria-label="Каталон — на главную"><img src={headerLogo} alt="Каталон" className="h-7 w-auto" /></a><nav className="hidden items-center gap-7 text-sm font-bold lg:flex">{links.map(([label, href]) => <a key={label} href={href} className="w-fit whitespace-nowrap transition hover:text-[#B7FF2A]">{label}</a>)}<div className="group relative"><button type="button" className="flex w-fit items-center gap-1 whitespace-nowrap text-sm font-bold transition group-hover:text-[#B7FF2A]">Для кого <ChevronDown className="h-4 w-4" /></button><div className="invisible absolute left-0 top-full mt-0 w-52 rounded-2xl border border-white/10 bg-[#2A0842] p-2 pt-3 opacity-0 shadow-2xl transition group-hover:visible group-hover:opacity-100">{[['Заказчикам','for-customers'],['Перевозчикам','for-carriers'],['Операторам','for-operators'],['Партнёрам','for-partners']].map(([label, path]) => <a key={label} href={baseUrl(path)} className="block w-fit rounded-xl px-3 py-2 text-sm font-bold text-white/80 transition hover:bg-white/10 hover:text-[#B7FF2A]">{label}</a>)}</div></div><a href={baseUrl('contacts')} className="w-fit whitespace-nowrap transition hover:text-[#B7FF2A]">Контакты</a></nav><div className="hidden items-center gap-3 lg:flex"><a href={baseUrl('login')} className="w-fit px-3 py-2 text-sm font-bold text-white/85 transition hover:text-[#B7FF2A]">Войти</a><a href={baseUrl('registration')} className="w-fit rounded-full bg-white px-5 py-2 text-sm font-bold text-[#440D84] transition hover:bg-[#B7FF2A]">Регистрация</a></div><button type="button" className="grid h-9 w-9 place-items-center rounded-full bg-white/10 lg:hidden" onClick={() => setOpen(!open)} aria-label="Открыть меню"><Menu className="h-5 w-5" /></button></div>{open && <nav className="grid gap-1 bg-[#440D84] px-4 pb-5 lg:hidden">{links.map(([label, href]) => <a key={label} href={href} className="border-t border-white/10 py-3 text-sm font-bold">{label}</a>)}<span className="border-t border-white/10 py-3 text-sm font-bold">Для кого</span>{[['Заказчикам','for-customers'],['Перевозчикам','for-carriers'],['Операторам','for-operators'],['Партнёрам','for-partners']].map(([label, path]) => <a key={label} href={baseUrl(path)} className="pl-4 text-sm font-bold text-white/75">{label}</a>)}<a href={baseUrl('contacts')} className="border-t border-white/10 py-3 text-sm font-bold">Контакты</a><a href={baseUrl('login')} className="py-2 text-sm font-bold">Войти</a><a href={baseUrl('registration')} className="rounded-full bg-white px-5 py-3 text-center text-sm font-bold text-[#440D84]">Регистрация</a></nav>}</header>;
}
