import { useEffect, useRef, useState, type ComponentProps } from 'react';
import { Archive, ArrowUpRight, BarChart3, BadgeDollarSign, Boxes, Building2, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardCheck, ClipboardList, Clock3, FileCheck2, FileStack, FileText, Fuel, Gauge, HandCoins, Landmark, LineChart, MapPin, Network, Route, Search, Settings2, ShieldCheck, Truck, UserRound, Users, WalletCards, Workflow, Wrench } from 'lucide-react';
import { UnifiedHeader } from './components/UnifiedHeader';
import { UnifiedFooter } from './components/UnifiedFooter';
const ArrowSmall = () => <ArrowUpRight size={14} />;

const Placeholder = ({ label, className = '' }: { label: string; className?: string }) => <div className={`carrier-placeholder ${className}`}><span>Место для изображения</span><b>{label}</b></div>;
const economics = [['Оплачиваемый пробег', 'Увеличивайте долю километров, за которые платит заказчик.', Truck], ['Ставка за километр', 'Сравнивайте предложения с учётом маршрута и условий перевозки.', BarChart3], ['Холостой пробег', 'Ищите попутную или обратную загрузку, чтобы машина меньше ехала без груза.', Route], ['Простой', 'Планируйте следующую перевозку до завершения текущей.', Clock3], ['Скорость оплаты', 'Учитывайте не только сумму, но и срок поступления денег.', WalletCards], ['Себестоимость рейса', 'Подключайте сервисы, снижающие расходы на топливо и транспорт.', Gauge]];
const benefits = [['Подходящие загрузки', 'Фильтруйте грузы по маршруту, дате, типу транспорта и параметрам перевозки.', Truck], ['Цепочка рейсов', 'Планируйте следующую загрузку с учётом текущего маршрута и точки выгрузки.', Route], ['Понятные условия', 'Сразу видите ставку, маршрут, сроки, требования и порядок оплаты.', FileText], ['Безопасная сделка', 'Условия, участники, события и документы связываются с конкретным рейсом.', ShieldCheck], ['Финансовые инструменты', 'Подключайте доступное финансирование или ускоренную оплату под перевозку.', HandCoins], ['Сервисы для транспорта', 'Получайте доступ к топливу, обслуживанию, страхованию и предложениям партнёров.', Workflow]];
const routeSteps = [['Добавьте транспорт', 'Укажите тип кузова, грузоподъёмность, регион работы и параметры автомобиля.', Truck], ['Найдите подходящий груз', 'Используйте поиск или рекомендации по маршруту и доступному транспорту.', MapPin], ['Проверьте условия', 'Оцените ставку, маршрут, сроки, требования заказчика и порядок оплаты.', FileCheck2], ['Подтвердите перевозку', 'Зафиксируйте договорённости и необходимые документы в карточке рейса.', CheckCircle2], ['Выполните рейс', 'Передавайте статусы погрузки, движения и выгрузки через цифровой кабинет.', Route], ['Закройте документы и расчёты', 'Передайте закрывающие документы и сохраните всю историю перевозки.', FileText]];
const loadFilters = [['Направление', Route], ['Дата погрузки', CalendarDays], ['Тип кузова', Truck], ['Грузоподъёмность', Gauge], ['Тип груза', Boxes], ['Ставка', BadgeDollarSign], ['Способ загрузки', Settings2], ['Температурный режим', Fuel], ['Срок оплаты', Clock3], ['Дополнительные требования', ClipboardList]];
const routeOptions = ['Попутные грузы', 'Обратные загрузки', 'Поиск рядом с точкой выгрузки', 'Временные интервалы', 'Расстояние до следующей погрузки', 'Последовательность рейсов', 'Предварительное планирование', 'Рекомендации по маршруту'];
const economyMetrics = [['Общая ставка', BadgeDollarSign], ['Ставка за километр', LineChart], ['Оплачиваемый пробег', Route], ['Холостой пробег', Truck], ['Расход топлива', Fuel], ['Платные дороги', Landmark], ['Время ожидания', Clock3], ['Срок оплаты', CalendarDays], ['Дополнительные расходы', CircleDollarSign], ['Итоговая экономика рейса', BarChart3]];
const paymentPoints = [['Заказчик и участники определены', ShieldCheck], ['Ставка и срок оплаты зафиксированы', FileCheck2], ['Этапы выполнения сохраняются', Route], ['Документы связаны с рейсом', FileStack], ['История действий доступна сторонам', HistoryIcon]];
const cabinetSections = [['Свободные грузы', 'Поиск доступных заявок по маршруту и параметрам транспорта.', Search], ['Мой транспорт', 'Автомобили, характеристики, документы и доступность.', Truck], ['Маршруты', 'Текущие и запланированные цепочки перевозок.', Route], ['Заявки и предложения', 'Условия участия и согласованные ставки.', ClipboardList], ['Рейсы', 'Маршрут, участники, статусы и ключевые события.', MapPin], ['Документы', 'Файлы и подтверждения по каждой перевозке.', FileText], ['Финансы', 'Условия оплаты, расчёты и финансовые инструменты.', CircleDollarSign], ['Сервисы', 'Полезные предложения для транспорта и бизнеса.', Workflow], ['История и аналитика', 'Выполненные рейсы, пробег, ставки и результаты работы.', LineChart]];
const carrierFaq = [
  ['Кто может зарегистрироваться как перевозчик?', 'ИП, транспортные компании, владельцы коммерческого грузового транспорта, соответствующие требованиям конкретной перевозки.'],
  ['Сколько стоит регистрация?', 'Регистрация и базовый доступ бесплатны. Вознаграждение Catalon применяется к успешно завершённым сделкам.'],
  ['Как подбираются грузы?', 'По маршруту, датам, характеристикам транспорта, типу груза и дополнительным требованиям.'],
  ['Можно ли выбирать только определённые направления?', 'Да, перевозчик указывает интересующие регионы и выбирает подходящие заявки.'],
  ['Можно ли искать обратную загрузку?', 'Учитываются точка выгрузки и следующие подходящие рейсы.'],
  ['Как фиксируется ставка?', 'Ставка, маршрут, сроки и порядок оплаты сохраняются в карточке перевозки.'],
  ['Catalon гарантирует оплату?', 'Catalon фиксирует условия и историю сделки; защита и финансирование зависят от продукта и конкретной перевозки.'],
  ['Можно ли получить деньги раньше срока?', 'Для отдельных перевозок доступны авансирование и ускоренная оплата, условия определяются индивидуально.'],
  ['Где хранятся документы?', 'Документы прикреплены к конкретному рейсу в электронном архиве.'],
  ['Какие сервисы доступны перевозчику?', 'Топливо, страхование, финансирование, лизинг, обслуживание, шины, запчасти, масла и юридическая поддержка.'],
  ['Может ли оператор помочь найти следующий груз?', 'Да, оператор помогает с заявками, маршрутом, документами и операционными вопросами.'],
  ['Можно ли подключить несколько автомобилей?', 'Да, автопарк можно добавить и управлять доступностью через кабинет.'],
];
function HistoryIcon(props: ComponentProps<typeof Clock3>) { return <Clock3 {...props} />; }
const pointIcons = [MapPin, FileCheck2, Route, ShieldCheck, WalletCards, Clock3, Users, Wrench] as const;
const PointIcon = ({ index, size = 17 }: { index: number; size?: number }) => { const Icon = pointIcons[index % pointIcons.length]; return <Icon size={size} />; };

export default function ForCarriersPage() {
  const [active, setActive] = useState('overview');
  const submenuRef = useRef<HTMLElement>(null);
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(false);
  const submenu = [['Обзор', 'overview'], ['Экономика', 'economy'], ['Преимущества', 'benefits'], ['Процесс', 'start'], ['Грузы', 'loads'], ['Маршруты', 'routes'], ['Аналитика', 'analytics'], ['Оплата', 'payment'], ['Кабинет', 'cabinet'], ['Команда', 'team'], ['Сервисы', 'services'], ['Защита', 'security'], ['Документы', 'documents'], ['Типы перевозчиков', 'types'], ['FAQ', 'faq']];
  const updateSubmenuScroll = () => { const el = submenuRef.current; if (!el) return; setCanScrollLeft(el.scrollLeft > 4); setCanScrollRight(el.scrollLeft + el.clientWidth < el.scrollWidth - 4); };
  const scrollSubmenu = (amount: number) => submenuRef.current?.scrollBy({ left: amount, behavior: 'smooth' });
  useEffect(() => { const el = submenuRef.current; const frame = window.requestAnimationFrame(updateSubmenuScroll); const observer = el && typeof ResizeObserver !== 'undefined' ? new ResizeObserver(updateSubmenuScroll) : null; if (el) { el.addEventListener('scroll', updateSubmenuScroll); observer?.observe(el); } window.addEventListener('resize', updateSubmenuScroll); return () => { window.cancelAnimationFrame(frame); el?.removeEventListener('scroll', updateSubmenuScroll); observer?.disconnect(); window.removeEventListener('resize', updateSubmenuScroll); }; }, []);
  useEffect(() => { document.title = 'Catalon для перевозчиков — грузы, рейсы и сервисы для автопарка'; const sections = submenu.map(([, id]) => document.getElementById(id)).filter(Boolean) as HTMLElement[]; const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-100px 0px -60% 0px' }); sections.forEach((section) => observer.observe(section)); return () => observer.disconnect(); }, []);
  return <div className="carrier-page"><UnifiedHeader /><div className="carrier-subnav-wrap"><button type="button" className={`carrier-subnav-arrow carrier-subnav-arrow-left `} aria-label="Прокрутить подменю влево" disabled={!canScrollLeft} onClick={() => scrollSubmenu(-320)}><ChevronLeft size={18} /></button><nav ref={submenuRef} className="carrier-subnav">{submenu.map(([label, id]) => <a key={id} className={active === id ? 'active' : ''} href={`#${id}`}>{label}</a>)}</nav><button type="button" className={`carrier-subnav-arrow carrier-subnav-arrow-right `} aria-label="Прокрутить подменю вправо" disabled={!canScrollRight} onClick={() => scrollSubmenu(320)}><ChevronRight size={18} /></button></div><main>
    <section id="overview" className="carrier-hero"><div className="carrier-container carrier-hero-grid"><div><p className="carrier-eyebrow">ДЛЯ ПЕРЕВОЗЧИКОВ И ТРАНСПОРТНЫХ КОМПАНИЙ</p><h1>Больше оплачиваемых километров. Меньше простоев и лишних расходов</h1><p className="carrier-lead">Находите загрузки под свой маршрут и транспорт, выстраивайте цепочки рейсов, фиксируйте условия и контролируйте оплату в едином цифровом кабинете. Catalon помогает повышать загрузку автопарка и снижать стоимость каждого километра.</p><div className="carrier-actions"><a className="carrier-btn carrier-btn-purple" href="#loads">Найти грузы</a><a className="carrier-btn carrier-btn-white" href="#cabinet">Подключить автопарк</a></div><div className="carrier-tags"><span>Грузы по маршруту</span><span>Попутные и обратные загрузки</span><span>Финансирование рейса</span><span>Документы онлайн</span><span>Сервисы для транспорта</span></div><p className="carrier-note">Бесплатная регистрация · Поддержка оператора · Работа по всей России</p></div><div className="carrier-hero-art"><Placeholder label="Везун, грузовик и интерфейс грузов" /><div className="carrier-status carrier-status-a">Найдена загрузка по маршруту</div><div className="carrier-status carrier-status-b">Рейс рассчитан</div><div className="carrier-status carrier-status-c">Оплата в процессе</div></div></div></section>
    <section className="carrier-stats"><div className="carrier-container carrier-stats-grid"><div><strong>0 ₽</strong><span>Регистрация и доступ к платформе.</span></div><div><strong>По маршруту</strong><span>Подбор загрузок под направление и параметры транспорта.</span></div><div><strong>Быстрее к оплате</strong><span>Финансовые инструменты под конкретную перевозку.</span></div><div><strong>Всё для рейса</strong><span>Топливо, страхование, обслуживание и документы в одной экосистеме.</span></div></div></section>
    <section id="economy" className="carrier-section carrier-warm"><div className="carrier-container"><div className="carrier-section-intro"><div><p className="carrier-eyebrow">ЭКОНОМИКА АВТОПАРКА</p><h2>Важно не сколько километров проехала машина, а сколько она заработала на каждом километре</h2><p>Большой пробег не гарантирует высокую прибыль. Каждый дополнительный километр увеличивает расходы на топливо, водителя, обслуживание и износ транспорта. Поэтому перевозчику важно одновременно управлять ставкой, загрузкой и себестоимостью рейса.</p></div><blockquote>Самая высокая ставка не всегда означает самый прибыльный рейс.</blockquote></div><div className="economy-grid"><div className="formula-card"><span>Пример расчёта</span><h3>Экономика рейса</h3><p>Выручка = оплачиваемый пробег × ставка за километр</p><p>Прибыль = выручка − расходы рейса</p><Placeholder label="Оплачиваемый и холостой пробег" /></div><div className="economy-cards">{economics.map(([title, text, Icon]) => <article key={title as string}><div className="carrier-icon"><Icon size={21} /></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></div></div></section>
    <section id="benefits" className="carrier-section"><div className="carrier-container"><p className="carrier-eyebrow">ЕДИНЫЙ РАБОЧИЙ КОНТУР</p><h2>Не просто список грузов, а система управления работой транспорта</h2><div className="benefit-grid">{benefits.map(([title, text, Icon], i) => <article className={`benefit-card benefit-card-${i + 1}`} key={title as string}><div className="carrier-icon"><Icon size={22} /></div><h3>{title as string}</h3><p>{text as string}</p>{i < 3 && <Placeholder label={i === 0 ? 'Карточка груза' : i === 1 ? 'Цепочка маршрутов' : 'Условия рейса'} />}</article>)}</div></div></section>
    <section id="start" className="carrier-section carrier-route"><div className="carrier-container"><p className="carrier-eyebrow">ОТ ГРУЗА ДО ОПЛАТЫ</p><h2>Весь рейс проходит в одном цифровом процессе</h2><div className="route-panel"><div className="route-line" />{routeSteps.map(([title, text, Icon], i) => <article key={title as string}><span className="route-number">0{i + 1}</span><div className="route-icon"><Icon size={21} /></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div><p className="route-result">Понятный маршрут · Зафиксированные условия · Единая история рейса.</p></div></section>
    <section id="loads" className="carrier-section carrier-loads"><div className="carrier-container"><div className="carrier-section-head"><div><p className="carrier-eyebrow">ЗАГРУЗКА ТРАНСПОРТА</p><h2>Находите рейсы, которые подходят вашему автомобилю</h2><p>Не нужно вручную просматривать сотни неподходящих заявок. Параметры груза сопоставляются с маршрутом, датой и характеристиками транспорта.</p></div><a className="carrier-btn carrier-btn-purple" href="#cabinet">Посмотреть доступные грузы</a></div><div className="loads-interface"><aside><b>Фильтры</b>{loadFilters.map(([label, Icon]) => <div key={label as string}><Icon size={16} /><span>{label as string}</span></div>)}</aside><div className="load-results"><div className="load-toolbar"><Search size={18} /><span>Москва → Казань</span><small>Демонстрационные данные</small></div>{[['Москва → Казань', '12 июня', 'Тент · 20 т', '128 000 ₽'], ['Нижний Новгород → Москва', '14 июня', 'Рефрижератор · 10 т', '92 000 ₽'], ['Казань → Екатеринбург', '16 июня', 'Штора · 20 т', '116 000 ₽']].map((load) => <article key={load[0]}><div><strong>{load[0]}</strong><span>{load[1]} · {load[2]}</span></div><b>{load[3]}</b><button type="button">Подробнее</button></article>)}</div></div></div></section>
    <section id="routes" className="carrier-section carrier-chain"><div className="carrier-container carrier-chain-grid"><div><p className="carrier-eyebrow">МЕНЬШЕ ХОЛОСТОГО ПРОБЕГА</p><h2>Планируйте не один рейс, а следующие точки загрузки</h2><p>После выгрузки автомобиль не должен оставаться без работы. Catalon помогает учитывать конечную точку маршрута и искать следующую подходящую перевозку.</p><div className="route-options">{routeOptions.map((item, i) => <span key={item}><PointIcon index={i} size={15} />{item}</span>)}</div><a className="carrier-btn carrier-btn-white" href="#loads">Построить цепочку</a></div><div className="chain-map"><p>Пример сценария</p><h3>Москва → Нижний Новгород → Казань → Москва</h3><div className="chain-route"><span>Москва<small>128 000 ₽ · 420 км</small></span><i /><span>Нижний Новгород<small>92 000 ₽ · 380 км</small></span><i /><span>Казань<small>116 000 ₽ · 790 км</small></span></div><div className="chain-metrics"><b>78%<small>оплачиваемого пробега</small></b><b>124 км<small>холостой пробег</small></b><b>6 дней<small>общий период цепочки</small></b></div></div></div></section>
    <section id="analytics" className="carrier-section carrier-economy"><div className="carrier-container carrier-economy-grid"><div><p className="carrier-eyebrow">РЕЙС В ЦИФРАХ</p><h2>Сравнивайте предложения по прибыли, а не только по общей ставке</h2><p>Две перевозки с одинаковой оплатой могут иметь разную экономику. На результат влияют расстояние до погрузки, холостой пробег, расход топлива, срок оплаты и простой между рейсами.</p><div className="economy-dashboard"><span>Пример самостоятельной оценки</span><div><b>Рейс A</b><strong>128 000 ₽</strong><small>Итоговая экономика рейса</small></div><div><b>Рейс B</b><strong>116 000 ₽</strong><small>Итоговая экономика рейса</small></div></div></div><div className="economy-metrics">{economyMetrics.map(([label, Icon]) => <article key={label as string}><Icon size={19} /><span>{label as string}</span><b>—</b></article>)}</div><p className="carrier-quote">Catalon помогает увидеть, что останется перевозчику после выполнения рейса, а не только сумму в заявке.</p></div></section>
    <section id="payment" className="carrier-section carrier-payment"><div className="carrier-container carrier-payment-grid"><div><p className="carrier-eyebrow">ДЕНЬГИ ЗА ВЫПОЛНЕННУЮ РАБОТУ</p><h2>Хорошая ставка имеет смысл, только если деньги поступают</h2><p>Перевозчику необходимо оплачивать топливо, водителя и обслуживание сегодня, даже если заказчик рассчитывается через несколько недель. Catalon связывает условия оплаты с конкретной перевозкой и помогает подключить подходящий финансовый инструмент.</p><div className="payment-columns"><div><h3>Уверенность в оплате</h3>{paymentPoints.map(([label, Icon]) => <span key={label as string}><Icon size={17} />{label as string}</span>)}</div><div><h3>Скорость получения денег</h3>{['Авансирование', 'Финансирование рейса', 'Ускоренная выплата', 'Другие доступные финансовые продукты'].map((label, i) => <span key={label}><PointIcon index={i + 4} size={17} />{label}</span>)}</div></div><p className="legal-note">Доступность, стоимость и сроки финансового решения определяются индивидуально.</p><a className="carrier-btn carrier-btn-purple" href="#cabinet">Узнать условия финансирования</a></div><Placeholder label="Кэшик, карточка рейса и таймлайн выплаты" /></div></section>
    <section id="cabinet" className="carrier-section carrier-cabinet"><div className="carrier-container"><p className="carrier-eyebrow">УПРАВЛЕНИЕ ПЕРЕВОЗКАМИ — ОНЛАЙН</p><h2>Грузы, рейсы, документы и расчёты — в одном кабинете</h2><div className="cabinet-interface"><aside>{cabinetSections.map(([label, , Icon], i) => <div className={i === 0 ? 'selected' : ''} key={label as string}><Icon size={18} /><span>{label as string}</span></div>)}</aside><div className="cabinet-screen"><small>Свободные грузы</small><h3>Подходящие загрузки для вашего транспорта</h3><Placeholder label="Главный экран кабинета перевозчика" /></div></div></div></section>
    <section id="team" className="carrier-section carrier-team"><div className="carrier-container carrier-team-grid"><div><p className="carrier-eyebrow">МАЛЕНЬКИМ — КАК БОЛЬШИМ</p><h2>Даже небольшой перевозчик получает инструменты полноценного транспортного бизнеса</h2><p>Собственнику одного автомобиля или небольшого парка сложно одновременно искать грузы, строить маршруты, проверять заказчиков, собирать документы и контролировать оплату. Catalon объединяет эти задачи в единой системе.</p><div className="carrier-team-points">{['Помощь оператора', 'Поиск следующей загрузки', 'Проверка условий сделки', 'Контроль сроков оплаты', 'Хранение документов', 'Финансовые сервисы', 'Юридическая поддержка', 'Сервисы для транспорта'].map((item, i) => <span key={item}><PointIcon index={i} />{item}</span>)}</div><strong className="carrier-team-note">Вы занимаетесь транспортом, а платформа помогает сократить операционную рутину вокруг него.</strong></div><Placeholder label="Единая очередь транспорта и рейсов" /></div></section>
    <section id="services" className="carrier-section carrier-services"><div className="carrier-container"><p className="carrier-eyebrow">ЭКОСИСТЕМА ДЛЯ ТРАНСПОРТА</p><h2>Каждый рейс приносит выручку — и одновременно создаёт расходы</h2><p className="carrier-intro-text">Грузовик постоянно потребляет топливо, шины, масла, запасные части и обслуживание. Catalon подключает партнёрские сервисы в контексте работы транспорта.</p><div className="carrier-service-grid">{[['Catalon Топливо', 'Специальные условия на топливо и контроль затрат по рейсам.', Fuel], ['Шины, запчасти и масла', 'Расходные материалы и комплектующие для коммерческого транспорта.', Wrench], ['Автосервис и шиномонтаж', 'Обслуживание транспорта через партнёрскую сеть.', Truck], ['Catalon Страхование', 'Страхование груза, транспорта и ответственности.', ShieldCheck], ['Catalon Финанс', 'Финансирование рейсов и поддержка оборотных средств.', WalletCards], ['Catalon Лизинг', 'Обновление и расширение автопарка.', Building2], ['Юридический сервис', 'Договоры, претензии, штрафы и спорные ситуации.', FileCheck2], ['Поддержка в пути', 'Помощь при операционных и технических вопросах.', HandCoins]].map(([title, text, Icon]) => <article key={title as string}><div className="carrier-icon"><Icon size={21} /></div><h3>{title as string}</h3><p>{text as string}</p><span className="service-status">Доступно <ArrowSmall /></span></article>)}</div><a className="carrier-text-link" href="#services">Посмотреть сервисы</a></div></section>
    <section id="security" className="carrier-section carrier-security"><div className="carrier-container carrier-security-banner"><div><p className="carrier-eyebrow">ПОНЯТНЫЕ УСЛОВИЯ</p><h2>Вы знаете, кому везёте, сколько получите и что требуется для оплаты</h2><p>До подтверждения перевозки участник должен видеть ключевые условия сделки. После согласования информация сохраняется в карточке рейса.</p><div className="security-grid">{['Заказчик', 'Маршрут', 'Параметры груза', 'Требования к транспорту', 'Ставка', 'Порядок и срок оплаты', 'Этапы выполнения', 'Документы', 'История изменений'].map((item, i) => <span key={item}><PointIcon index={i} size={16} />{item}</span>)}</div></div><Placeholder label="Карточка участника, маршрут и условия" /></div></section>
    <section id="documents" className="carrier-section carrier-docs"><div className="carrier-container carrier-docs-grid"><Placeholder label="Папка, документы и электронная подпись" /><div><p className="carrier-eyebrow">БЕЗ БУМАЖНОЙ ПУТАНИЦЫ</p><h2>Документы не теряются после выгрузки</h2><p>Заявка, согласованные условия, транспортные и закрывающие документы хранятся в карточке рейса. Перевозчику не нужно восстанавливать историю по сообщениям, фотографиям и электронной почте.</p><div className="docs-points">{['Загрузка документов по рейсу', 'Контроль комплектности', 'Актуальный статус', 'История версий', 'Электронный архив', 'Передача заказчику', 'Доступ бухгалтерии', 'Повторное использование реквизитов и шаблонов'].map((item, i) => <span key={item}><PointIcon index={i} />{item}</span>)}</div></div></div></section>
    <section id="types" className="carrier-section carrier-types"><div className="carrier-container"><p className="carrier-eyebrow">РАСТЁМ ВМЕСТЕ С АВТОПАРКОМ</p><h2>Полезно и для одной машины, и для транспортной компании</h2><div className="carrier-type-grid">{[['Собственник-водитель', 'Находить загрузки, проверять условия, передавать документы и контролировать оплату.', UserRound], ['Небольшой автопарк', 'Планировать занятость нескольких машин, выстраивать цепочки рейсов и использовать поддержку оператора.', Truck], ['Компания с диспетчерами', 'Разделять задачи между сотрудниками, контролировать транспорт и сохранять общую историю работы.', Users], ['Развивающийся перевозчик', 'Подключать финансирование, лизинг, сервисы и расширять круг заказчиков.', Network]].map(([title, text, Icon]) => <article key={title as string}><div className="type-visual"><Icon size={34} /></div><h3>{title as string}</h3><p>{text as string}</p><a href="#cabinet">Подходит мне</a></article>)}</div></div></section>
    <section id="connect" className="carrier-section carrier-connect"><div className="carrier-container carrier-connect-panel"><p className="carrier-eyebrow">БЫСТРЫЙ СТАРТ</p><h2>Добавьте транспорт и найдите первую загрузку</h2><div className="carrier-connect-steps">{[['01', 'Зарегистрируйтесь', 'Создайте профиль перевозчика или транспортной компании.', Building2], ['02', 'Добавьте транспорт', 'Укажите характеристики автомобилей и направления работы.', Truck], ['03', 'Выберите груз', 'Найдите подходящую заявку и изучите условия.', Search], ['04', 'Подтвердите рейс', 'Зафиксируйте договорённости и приступайте к перевозке.', CheckCircle2]].map(([number, title, text, Icon]) => <article key={number as string}><b className="connect-number">{number as string}</b><div className="connect-icon"><Icon size={23} /></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div><div className="carrier-actions carrier-connect-actions"><a className="carrier-btn carrier-btn-purple" href="#loads">Найти грузы</a><a className="carrier-btn carrier-btn-white" href="#cabinet">Подключить автопарк</a></div></div></section>
    <section id="faq" className="carrier-section carrier-faq"><div className="carrier-container carrier-faq-grid"><div><p className="carrier-eyebrow">ОТВЕТЫ НА ВОПРОСЫ</p><h2>Всё, что важно знать перед подключением</h2><div className="carrier-faq-list">{carrierFaq.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div><aside className="carrier-support-card"><div className="carrier-icon"><Users size={22} /></div><h3>Остались вопросы?</h3><p>Оператор поможет разобраться с регистрацией, заявками, документами и первым рейсом.</p><a className="carrier-text-link" href="#connect">Получить консультацию <ArrowSmall /></a></aside></div></section>
    <section id="final" className="carrier-final-cta"><div><p className="carrier-eyebrow">ПУСТЬ КАЖДЫЙ КИЛОМЕТР РАБОТАЕТ НА БИЗНЕС</p><h2>Загрузите транспорт выгоднее вместе с Catalon</h2><p>Добавьте автомобиль или подключите автопарк, чтобы находить подходящие грузы, контролировать рейсы и использовать сервисы транспортной экосистемы.</p><div className="carrier-actions"><a className="carrier-btn carrier-btn-lime" href="#loads">Найти грузы</a><a className="carrier-btn carrier-btn-outline" href="#connect">Подключить автопарк</a></div></div><Placeholder label="Везун, грузовик и следующая загрузка" className="carrier-final-art" /></section>
  </main><UnifiedFooter /></div>;
}
