import { UnifiedHeader } from './components/UnifiedHeader';
import { UnifiedFooter } from './components/UnifiedFooter';
import { useEffect, useRef, useState, type ComponentProps } from 'react';
import { Archive, BarChart3, BriefcaseBusiness, Calculator, CheckCircle2, ChevronLeft, ChevronRight, Clock3, FileCheck2, FileText, Gauge, HandCoins, Headphones, History, Route, ShieldCheck, Truck, Users, WalletCards, Workflow } from 'lucide-react';

const tasks = [['Организовать вывоз', 'Найти подходящий транспорт под маршрут, груз, сроки и требования.'], ['Уложиться в бюджет', 'Получить несколько предложений, сравнить условия и зафиксировать стоимость.'], ['Соблюсти сроки', 'Видеть ключевые этапы перевозки и вовремя реагировать на отклонения.'], ['Снизить риски', 'Проверять данные участников и сохранять историю взаимодействия.'], ['Собрать документы', 'Хранить транспортные и закрывающие документы вместе с перевозкой.'], ['Понять экономику', 'Сравнивать план и факт, историю ставок и затраты по направлениям.']];
const steps = [['Создать заявку', 'Указать маршрут, груз, даты, требования к транспорту и условия перевозки.'], ['Получить предложения', 'Собрать доступные варианты от перевозчиков и операторов.'], ['Выбрать исполнителя', 'Сравнить стоимость, условия, транспорт и данные участника.'], ['Зафиксировать условия', 'Сохранить ставку, сроки, этапы и ответственность сторон.'], ['Контролировать выполнение', 'Следить за назначением транспорта, погрузкой, движением и выгрузкой.'], ['Закрыть перевозку', 'Получить документы, завершить расчёты и сохранить историю сделки.']];
const Placeholder = ({ label, className = '' }: { label: string; className?: string }) => <div className={`visual-placeholder ${className}`}><span>Место для изображения</span><b>{label}</b></div>;
const taskIcons = [Truck, WalletCards, Clock3, ShieldCheck, FileCheck2, BarChart3];
const featureIcons = [FileText, BriefcaseBusiness, Truck, Route, Gauge, FileCheck2, Calculator, History, Headphones];
const teamIcons = [FileText, Workflow, Users, BellIcon, History, BarChart3, Headphones, Archive];
function BellIcon(props: ComponentProps<typeof Workflow>) { return <Workflow {...props} />; }
const Icon = ({ icon: Component }: { icon: typeof Workflow }) => <Component size={22} strokeWidth={1.8} aria-hidden="true" />;
function FeatureList({ items, icons = featureIcons }: { items: string[]; icons?: Array<typeof Workflow> }) { return <ul className="feature-list">{items.map((item, i) => <li key={item}><span className="feature-list-icon"><Icon icon={icons[i % icons.length]} /></span><span>{item}</span></li>)}</ul>; }
const faq = [['Какие перевозки можно организовать через Catalon?', 'Сейчас на платформе представлены автомобильные перевозки по России и мультимодальные маршруты. Новые логистические решения будут подключаться по мере развития маркетплейса.'], ['Catalon — перевозчик или биржа грузов?', 'Catalon — цифровая платформа для организации и управления перевозками. Исполнение выполняют выбранные участники, а платформа связывает заявку, условия, этапы, расчёты и документы.'], ['Можно ли сравнить предложения перевозчиков?', 'Да. Полученные предложения отображаются в рамках одной заявки, чтобы заказчик мог сравнить стоимость и условия.'], ['Как фиксируются условия перевозки?', 'Согласованная стоимость, маршрут, сроки, участники и требования сохраняются в карточке перевозки.'], ['Что включает безопасная сделка?', 'Фиксацию условий, данных участников, этапов исполнения, документов и истории изменений.'], ['Где хранятся документы?', 'Документы прикрепляются к конкретной перевозке и сохраняются в цифровом архиве.'], ['Сколько стоит подключение?', 'Регистрация бесплатная. Вознаграждение платформы применяется к успешно завершённым сделкам. Точные условия показываются до подтверждения перевозки.'], ['Можно ли подключить финансирование?', 'Доступность и условия финансовых инструментов определяются индивидуально с учётом параметров перевозки и участника.'], ['Может ли оператор помочь с заявкой?', 'Да. Оператор может помочь при подключении, оформлении перевозки и решении операционных вопросов.'], ['Можно ли работать полностью онлайн?', 'Основные действия — заявка, предложения, статусы, документы и история перевозки — доступны через цифровой кабинет Catalon.']];

export default function ForCustomersPage() {
  const [activeSection, setActiveSection] = useState('overview');
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(false);
  const submenuRef = useRef<HTMLElement>(null);
  const submenu = [['Обзор', 'overview'], ['Задачи', 'tasks'], ['Как работает', 'flow'], ['Решения', 'solutions'], ['Кабинет', 'cabinet'], ['Контроль', 'control'], ['Экономика', 'economy'], ['Безопасность', 'security'], ['Документы', 'documents'], ['Сервисы', 'services'], ['FAQ', 'faq']];
  useEffect(() => {
    const sections = submenu.map(([, id]) => document.getElementById(id)).filter(Boolean) as HTMLElement[];
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) setActiveSection(entry.target.id); }), { rootMargin: '-128px 0px -55% 0px', threshold: 0 });
    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const element = submenuRef.current;
    if (!element) return;
    const update = () => { setCanScrollLeft(element.scrollLeft > 4); setCanScrollRight(Math.ceil(element.scrollLeft + element.clientWidth) < element.scrollWidth - 4); };
    const frame = window.requestAnimationFrame(update);
    const observer = typeof ResizeObserver !== 'undefined' ? new ResizeObserver(update) : null;
    const leftArrow = document.querySelector('.customer-subnav-arrow-left');
    const rightArrow = document.querySelector('.customer-subnav-arrow-right');
    const moveLeft = () => { element.scrollLeft = Math.max(0, element.scrollLeft - 260); };
    const moveRight = () => { element.scrollLeft = Math.min(element.scrollWidth - element.clientWidth, element.scrollLeft + 260); };
    element.addEventListener('scroll', update, { passive: true });
    observer?.observe(element);
    window.addEventListener('resize', update);
    leftArrow?.addEventListener('click', moveLeft);
    rightArrow?.addEventListener('click', moveRight);
    return () => { window.cancelAnimationFrame(frame); element.removeEventListener('scroll', update); observer?.disconnect(); window.removeEventListener('resize', update); leftArrow?.removeEventListener('click', moveLeft); rightArrow?.removeEventListener('click', moveRight); };
  }, []);
  useEffect(() => {
    document.title = 'Catalon для заказчиков — управление грузоперевозками онлайн';
    const description = 'Размещайте заявки, сравнивайте предложения, контролируйте перевозки, расчёты и документы в едином цифровом кабинете Catalon.';
    let meta = document.querySelector('meta[name="description"]');
    if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.appendChild(meta); }
    meta.setAttribute('content', description);
  }, []);
  return <div className="customer-page"><UnifiedHeader />
    <div className="customer-subnav-wrap"><button type="button" className={`customer-subnav-arrow customer-subnav-arrow-left ${canScrollLeft ? '' : 'is-hidden'}`} disabled={!canScrollLeft} onClick={() => submenuRef.current?.scrollBy({ left: -260, behavior: 'smooth' })} aria-label="Прокрутить подменю влево"><ChevronLeft size={17} /></button><nav ref={submenuRef} className="customer-subnav">{submenu.map(([label, id]) => <a key={id} className={activeSection === id ? 'active' : ''} href={`#${id}`}>{label}</a>)}</nav><button type="button" className={`customer-subnav-arrow customer-subnav-arrow-right ${canScrollRight ? '' : 'is-hidden'}`} disabled={!canScrollRight} onClick={() => submenuRef.current?.scrollBy({ left: 260, behavior: 'smooth' })} aria-label="Прокрутить подменю вправо"><ChevronRight size={17} /></button></div>
    <main>
      <section id="overview" className="customer-hero"><div className="customer-container hero-grid"><div><p className="eyebrow">ДЛЯ ЗАКАЗЧИКОВ И ГРУЗООТПРАВИТЕЛЕЙ</p><h1>Перевозки под контролем — от заявки до закрывающих документов</h1><p className="lead">Создавайте заявку один раз, получайте предложения от перевозчиков и операторов, фиксируйте условия и контролируйте исполнение в едином цифровом кабинете. Все события, расчёты и документы остаются связанными с конкретной перевозкой.</p><div className="actions"><a className="btn btn-purple" href="#connect">Разместить заявку</a><a className="btn btn-light" href="#flow">Посмотреть, как работает</a></div><div className="hero-tags"><span>FTL и LTL</span><span>Мультимодальные маршруты</span><span>Безопасная сделка</span><span>Документы онлайн</span><span>Финансовые сервисы</span></div><p className="hero-note">Бесплатная регистрация · Оплата по результату · Поддержка оператора</p></div><div className="hero-art"><Placeholder label="Боксик с планшетом и грузом" className="hero-visual" />{['Получено 5 предложений', 'Условия согласованы', 'Погрузка подтверждена', 'Документы готовы'].map((label, i) => <div key={label} className={`hero-status status-${i + 1}`}>{label}</div>)}</div></div></section>
      <section className="stats"><div>0 ₽<small>Регистрация и доступ к платформе.</small></div><div>Одна заявка<small>Условия, предложения и участники в одной карточке.</small></div><div>Всё онлайн<small>Статусы, события и документы доступны в кабинете.</small></div><div>По результату<small>Комиссия применяется к успешно завершённой сделке.</small></div></section>
      <section id="tasks" className="customer-section"><div className="customer-container"><p className="eyebrow">ЗАДАЧИ БИЗНЕСА</p><h2>Вам нужна не просто машина — вам нужен предсказуемый результат</h2><p className="section-lead">Задача грузоотправителя — обеспечить вывоз, уложиться в бюджет, выполнить обязательства перед получателем и сохранить полный комплект документов. Catalon связывает эти задачи в один процесс.</p><div className="task-grid">{tasks.map(([title, text], i) => <article key={title}><span className="card-number">0{i + 1}</span><div className="card-icon"><Icon icon={taskIcons[i]} /></div><h3>{title}</h3><p>{text}</p></article>)}</div><p className="quote-note">Catalon превращает разрозненные звонки, таблицы, переписки и документы в управляемый цифровой процесс.</p></div></section>
      <section id="flow" className="customer-section soft"><div className="customer-container"><p className="eyebrow">ЕДИНЫЙ СЦЕНАРИЙ</p><h2>Одна заявка проходит весь путь вместе с грузом</h2><div className="steps">{steps.map(([title, text], i) => <article key={title}><span>0{i + 1}</span><div className="step-icon"><Icon icon={[FileText, HandCoins, Users, CheckCircle2, Route, Archive][i]} /></div><h3>{title}</h3><p>{text}</p></article>)}</div><p className="result-note">Результат: единый контекст перевозки без разрозненных чатов, файлов и таблиц.</p></div></section>
      <section id="solutions" className="customer-section"><div className="customer-container"><p className="eyebrow">ФОРМАТЫ ПЕРЕВОЗОК</p><h2>Выбирайте решение под маршрут и груз</h2><div className="solution-grid"><article><Placeholder label="Автомобильные перевозки по РФ" /><h3>Автомобильные перевозки по РФ</h3><p>FTL- и LTL-перевозки, поиск транспорта, сравнение предложений, контроль рейса и документы.</p><div className="mini-tags"><span>Прямые перевозки</span><span>Полная и частичная загрузка</span><span>Перевозки по России</span></div><a className="text-link" href="/road-freight-russia">Подробнее об автоперевозках</a></article><article><Placeholder label="Мультимодальный маршрут" /><h3>Мультимодальные перевозки</h3><p>Автомобильные, железнодорожные, морские и терминальные этапы в единой маршрутной цепочке.</p><div className="mini-tags"><span>Контейнерные перевозки</span><span>Комбинированные маршруты</span><span>Контроль переходов</span></div><a className="text-link" href="/multimodal-container">Подробнее о мультимодальных</a></article></div><a className="all-solutions" href="#solutions">Посмотреть все решения Catalon</a></div></section>
      <section id="cabinet" className="customer-section cabinet"><div className="customer-container feature-grid"><div><p className="eyebrow">ЦИФРОВОЙ КАБИНЕТ</p><h2>Вся операционная работа — в одном интерфейсе</h2><p className="section-lead">Вам не нужно восстанавливать историю перевозки по сообщениям и файлам. Карточка заявки связывает участников, условия, этапы, расчёты и документы.</p><FeatureList items={['Заявки', 'Предложения и тарифы', 'Перевозчики и транспорт', 'Рейсы и статусы', 'События и отклонения', 'Документы', 'Расчёты', 'История и аналитика', 'Поддержка оператора']} /></div><Placeholder label="Реальный скриншот портала Catalon" className="cabinet-visual" /></div></section>
      <section id="control" className="customer-section purple-panel"><div className="customer-container feature-grid"><div><p className="eyebrow">ПЕРЕВОЗКА В РЕАЛЬНОМ ВРЕМЕНИ</p><h2>Статус понятен без звонка «где машина?»</h2><p>Каждый этап имеет статус, срок, ответственного участника и связанные документы. Заказчик видит общую картину и подключается тогда, когда действительно требуется решение.</p><FeatureList items={['Фиксация ключевых событий', 'Контроль плановых и фактических сроков', 'Уведомления об отклонениях', 'История изменений', 'Передача ответственности между участниками']} /></div><div className="control-demo"><div className="status-line">Заявка создана → Условия подтверждены → Транспорт назначен → Погрузка → В пути → Выгрузка → Документы → Завершено</div><Placeholder label="Интерфейс контроля маршрута" /></div></div></section>
      <section id="economy" className="customer-section soft"><div className="customer-container feature-grid reverse"><div><p className="eyebrow">УПРАВЛЕНИЕ БЮДЖЕТОМ</p><h2>Планируйте расходы на основе истории перевозок</h2><p className="section-lead">Стоимость логистики влияет на себестоимость товара и финансовое планирование. Catalon помогает сохранять фактические ставки и формировать собственную базу для сравнения направлений, периодов и исполнителей.</p><ul className="feature-list">{['Сравнение предложений по одной заявке', 'Фиксация согласованной стоимости', 'План-факт по перевозке', 'История ставок по направлениям', 'Динамика стоимости по периодам', 'Анализ сезонных изменений', 'Расходы по маршрутам и исполнителям', 'Выгрузка данных для закупок и финансовой службы'].map(item => <li key={item}>{item}</li>)}</ul><p className="quote-note">Прогноз не берётся из воздуха: его основой становится накопленная история фактических перевозок компании.</p></div><Placeholder label="График динамики ставки по месяцам" /></div></section>
      <section id="security" className="customer-section purple-panel"><div className="customer-container feature-grid"><div><p className="eyebrow">ЗАЩИТА ИНТЕРЕСОВ СТОРОН</p><h2>Условия зафиксированы, участники определены, история сохраняется</h2><p>Данные заявки, согласованные условия, участники и документы связываются с конкретной перевозкой. Это уменьшает неоднозначность и помогает восстановить последовательность действий при спорной ситуации.</p><ul className="feature-list">{['Реквизиты и данные участников', 'Согласованные условия перевозки', 'Назначенный транспорт', 'Статусы выполнения', 'История изменений', 'Документы по сделке', 'Поддержка при возникновении вопросов'].map(item => <li key={item}>{item}</li>)}</ul></div><Placeholder label="Рут со щитом, проверкой и документами" /></div></section>
      <section id="documents" className="customer-section"><div className="customer-container feature-grid reverse"><Placeholder label="Документы и единый архив" /><div><p className="eyebrow">ДОКУМЕНТЫ И ЭДО</p><h2>Документы связаны с перевозкой, а не разбросаны по почте и чатам</h2><p className="section-lead">Заявка, условия, подтверждения, транспортные и закрывающие документы хранятся в карточке перевозки. Команда видит актуальные версии и может восстановить всю историю работы.</p><ul className="feature-list">{['Заявка', 'Согласованные условия', 'Подтверждения этапов', 'Транспортные документы', 'Электронные документы', 'Закрывающие документы', 'История изменений', 'Единый архив'].map(item => <li key={item}>{item}</li>)}</ul></div></div></section>
      <section className="customer-section finance"><div className="customer-container feature-grid"><div><p className="eyebrow">ФИНАНСИРОВАНИЕ</p><h2>Финансовое решение, связанное с конкретной перевозкой</h2><p className="section-lead">Если логистическая нагрузка создаёт кассовый разрыв, к заявке можно подключить доступные финансовые инструменты. Параметры перевозки, сумма и документы остаются внутри единого рабочего контура.</p><ul className="feature-list">{['Решение под реальную перевозку', 'Понятная связь финансирования с заявкой', 'Документы в одном месте', 'Контроль расчётов', 'Индивидуальные условия'].map(item => <li key={item}>{item}</li>)}</ul><a className="btn btn-purple" href="#connect">Узнать условия</a></div><Placeholder label="Кэшик, заявка, калькулятор и документы" /></div></section>
      <section className="customer-section"><div className="customer-container bento-grid"><div className="bento-main"><p className="eyebrow">МЕНЬШЕ РУТИНЫ</p><h2>Команда управляет отклонениями, а не собирает статусы вручную</h2><p className="section-lead">Catalon снижает объём повторяющейся операционной работы и помогает одному специалисту видеть больше перевозок без потери контекста.</p><Placeholder label="Единый интерфейс работы команды" /></div>{['Шаблоны повторных заявок', 'Единая очередь перевозок', 'Роли и зоны ответственности', 'Статусы и уведомления', 'История действий', 'Отчёты по выполненной работе', 'Поддержка оператора', 'Централизованный архив'].map((label, i) => <article key={label}><div className="card-icon"><Icon icon={teamIcons[i]} /></div><h3>{label}</h3></article>)}</div></section>
      <section id="services" className="customer-section soft"><div className="customer-container"><p className="eyebrow">ЭКОСИСТЕМА CATALON</p><h2>Подключайте дополнительные сервисы в контексте перевозки</h2><div className="service-grid">{[['Catalon Страхование', 'Защита груза и ответственности участников сделки.', ShieldCheck], ['Catalon Финанс', 'Финансовые инструменты под задачи перевозки и бизнеса.', WalletCards], ['Юридический сервис', 'Договоры, претензии, споры и сопровождение сделок.', FileCheck2], ['Поддержка оператора', 'Помощь при подключении, работе с заявкой и отклонениях.', Headphones]].map(([title, text, ServiceIcon]) => <article key={title as string}><div className="service-icon"><Icon icon={ServiceIcon as typeof Workflow} /></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div><a className="text-link" href="#services">Посмотреть все сервисы</a></div></section>
      <section className="customer-section"><div className="customer-container"><h2>Платформа подходит, если вы…</h2><div className="scenario-grid">{['Регулярно отправляете грузы по России', 'Работаете с несколькими маршрутами и подрядчиками', 'Проводите закупки или сравниваете предложения', 'Планируете логистический бюджет заранее', 'Хотите масштабировать перевозки без раздувания штата', 'Используете автомобильные и мультимодальные маршруты', 'Хотите контролировать документы и налоговые риски', 'Устали собирать статусы по телефону и в мессенджерах'].map((label, i) => <article key={label}><span>0{i + 1}</span><div className="scenario-icon"><Icon icon={[Truck, Route, BarChart3, Calculator, Users, Workflow, ShieldCheck, Headphones][i]} /></div><h3>{label}</h3></article>)}</div></div></section>
      <section id="connect" className="customer-section connect"><div className="customer-container connect-inner"><div className="connect-heading"><p className="eyebrow">БЫСТРЫЙ СТАРТ</p><h2>Начните с одной перевозки</h2><p>Четыре шага — и вся перевозка в цифровом контуре Catalon.</p></div><div className="connect-steps"><div><span>01</span><Icon icon={BriefcaseBusiness} /><b>Зарегистрируйте компанию</b></div><div><span>02</span><Icon icon={FileText} /><b>Создайте первую заявку</b></div><div><span>03</span><Icon icon={BarChart3} /><b>Получите и сравните предложения</b></div><div><span>04</span><Icon icon={Route} /><b>Запустите перевозку в цифровом контуре</b></div></div><div className="actions"><a className="btn btn-purple" href="#overview">Разместить заявку</a><a className="btn btn-light" href="#faq">Получить консультацию</a></div></div></section>
      <section id="faq" className="customer-section faq"><div className="customer-container"><p className="eyebrow">FAQ</p>{faq.map(([question, answer], i) => <details key={question} open={i === 0}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
      <section className="customer-cta" id="final-cta"><div><p className="eyebrow">СЛЕДУЮЩАЯ ПЕРЕВОЗКА МОЖЕТ БЫТЬ ПРОЩЕ</p><h2>Возьмите под контроль следующую перевозку</h2><p>Создайте заявку или обсудите с командой Catalon, как встроить платформу в ваши текущие логистические процессы.</p><div className="actions"><a className="btn btn-lime" href="#overview">Разместить заявку</a><a className="btn btn-outline" href="#connect">Получить консультацию</a></div></div></section>
    </main><UnifiedFooter /></div>;
}
