import { ClipboardList, CreditCard, Fuel, HelpCircle, Map, Shield, ShoppingBag, TrendingDown, Users, Wallet, Wrench } from 'lucide-react';
import earningImage from '../4.png';
import savingImage from '../5.png';
import safeDealImage from '../6.png';
import financeImage from '../7.png';
import businessImage from '../8.png';
import { ServiceCard } from './components/ServiceCard';

const Item = ({ icon: Icon, children }: { icon: typeof ClipboardList; children: string }) => <li className="flex items-center gap-3 text-sm text-[#675F6F]"><Icon className="h-4 w-4 shrink-0 text-[#5B20B5]" />{children}</li>;

export function HomeEarnSaveBlock() {
  return <section data-block-id="home-earn-save" data-block-title="Catalon помогает зарабатывать и экономить" className="mx-auto max-w-7xl rounded-[36px] bg-gray-50 px-4 py-16 lg:px-8 lg:py-24"><h2 className="text-center text-3xl font-bold">Catalon помогает зарабатывать и экономить</h2><p className="mx-auto mt-4 max-w-2xl text-center text-[#675F6F]">Решения открывают новые направления для заработка, а сервисы помогают снижать расходы на перевозки, транспорт и обслуживание бизнеса.</p><div className="mt-12 grid gap-8 lg:grid-cols-2"><article className="overflow-hidden rounded-[36px] border border-gray-100 bg-white p-8 shadow-sm"><h3 className="text-2xl font-bold">Решения помогают зарабатывать</h3><p className="mt-4 text-[#675F6F]">Получайте грузы, выходите на новые направления, загружайте транспорт и работайте с заказами через цифровой портал Catalon.</p><ul className="mt-7 space-y-4"><Item icon={ClipboardList}>Заявки и рейсы</Item><Item icon={Map}>Новые маршруты</Item><Item icon={Users}>Доступ к заказчикам</Item><Item icon={Shield}>Безопасная сделка</Item><Item icon={CreditCard}>Финансирование поездки</Item></ul><img src={earningImage} alt="Решения помогают зарабатывать" className="mt-8 h-auto w-full object-contain" /></article><article className="overflow-hidden rounded-[36px] border border-gray-100 bg-white p-8 shadow-sm"><h3 className="text-2xl font-bold">Сервисы помогают экономить</h3><p className="mt-4 text-[#675F6F]">Подключайте топливо, страхование, лизинг, запчасти, автосервис и юридическую поддержку внутри одной экосистемы.</p><ul className="mt-7 space-y-4"><Item icon={TrendingDown}>Снижение расходов</Item><Item icon={Fuel}>Топливные программы</Item><Item icon={Wrench}>Сервисы для автопарка</Item><Item icon={Wallet}>Финансовые инструменты</Item><Item icon={HelpCircle}>Поддержка бизнеса</Item></ul><img src={savingImage} alt="Сервисы помогают экономить" className="mt-8 h-auto w-full object-contain" /></article></div></section>;
}

export function HomeSafeDealBlock() {
  return <section data-block-id="home-safe-deal" data-block-title="Безопасная сделка — ключевое отличие Catalon" className="mx-auto max-w-7xl rounded-[36px] bg-[#7133D0] px-4 py-16 text-white lg:px-8 lg:py-24"><h2 className="text-center text-3xl font-bold"><span className="text-[#B7FF2A]">Безопасная сделка</span> — ключевое отличие Catalon</h2><p className="mx-auto mt-4 max-w-2xl text-center text-white/70">На рынке грузоперевозок многое до сих пор держится на звонках, переписках и личных договоренностях. Catalon переводит сделку в прозрачный онлайн-контур.</p><div className="mt-12 grid items-center gap-10 lg:grid-cols-2"><div className="grid gap-5 sm:grid-cols-2">{[['Фиксация условий','Маршрут, стоимость, сроки, участники и ключевые условия перевозки сохраняются внутри платформы.'],['Документы онлайн','Заявки, договоры и закрывающие документы хранятся в одном месте.'],['Контроль этапов','Участники видят статусы перевозки и ключевые шаги сделки.'],['Меньше рисков','Catalon помогает снизить риск неоплаты, срыва перевозки и потери документов.']].map(([title,text])=><article key={title} className="rounded-[28px] border border-white/10 bg-white/5 p-6"><h3 className="font-bold text-[#B7FF2A]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/75">{text}</p></article>)}</div><img src={safeDealImage} alt="Безопасная сделка Catalon" className="h-auto w-full object-contain" /></div></section>;
}

export function HomeTripFinanceBlock() {
  return <section data-block-id="home-trip-finance" data-block-title="Финансирование поездки под конкретный рейс" className="mx-auto max-w-7xl rounded-[48px] bg-[#BA9AF0] p-8 lg:p-14"><div className="grid items-center gap-10 lg:grid-cols-2"><div><div className="flex flex-wrap gap-2 text-xs font-bold text-white"><span className="rounded-full bg-white/20 px-4 py-2">Рейс</span><span className="rounded-full bg-white/20 px-4 py-2">Топливо</span><span className="rounded-full bg-white/20 px-4 py-2">Расходы</span><span className="rounded-full bg-white/20 px-4 py-2">Оплата</span></div><h2 className="mt-7 text-4xl font-extrabold text-[#1B1241]">Финансирование поездки<br /><span className="text-white">под конкретный рейс</span></h2><p className="mt-5 leading-7 text-white">Перевозчику не всегда удобно ждать оплату неделями. Catalon помогает закрывать расходы на рейс: топливо, дорогу, обслуживание и другие операционные затраты.</p><ul className="mt-7 space-y-4"><Item icon={CreditCard}>Деньги под конкретную перевозку</Item><Item icon={Wallet}>Помощь при кассовом разрыве</Item><Item icon={ShoppingBag}>Возможность брать больше заказов</Item><Item icon={TrendingDown}>Меньше зависимости от долгих отсрочек</Item><Item icon={Shield}>Финансовая поддержка внутри marketplace</Item></ul><button className="mt-8 rounded-full bg-[#B7FF2A] px-7 py-4 font-bold text-[#241044]">Узнать о финансировании</button></div><img src={financeImage} alt="Финансирование поездки" className="h-auto w-full object-contain" /></div></section>;
}

export function HomeBigBusinessToolsBlock() { return <section data-block-id="home-big-business-tools" data-block-title="Возможности больших компаний — для малого и среднего бизнеса" className="mx-auto max-w-7xl rounded-[36px] bg-[#350375] px-8 py-16 text-white lg:px-16 lg:py-20"><div className="grid items-center gap-10 lg:grid-cols-2"><div><h2 className="text-4xl font-extrabold"><span className="text-[#B7FF2A]">Возможности</span> больших компаний — для малого и среднего бизнеса</h2><p className="mt-6 leading-7 text-white/75">Catalon помогает небольшим перевозчикам и компаниям получать доступ к инструментам, которые обычно доступны крупным игрокам: финансированию, сервисам, безопасным сделкам, топливным программам и цифровому документообороту.</p><ul className="mt-8 grid gap-4 sm:grid-cols-2"><Item icon={CreditCard}>Финансирование рейсов</Item><Item icon={Fuel}>Топливные программы</Item><Item icon={Shield}>Страхование</Item><Item icon={Wallet}>Лизинг</Item><Item icon={Wrench}>Сервисы для транспорта</Item><Item icon={ClipboardList}>Документы онлайн</Item><Item icon={Shield}>Безопасные сделки</Item></ul></div><img src={businessImage} alt="Возможности больших компаний для малого и среднего бизнеса" className="h-auto w-full object-contain" /></div></section>; }

export function HomeServicesBlock() { const cards = [['Catalon Топливо', 'Снижайте расходы на топливо и контролируйте затраты на рейсы.', 'from-[#FFD43B] to-[#F59E0B]', 'Экономия'], ['Catalon Финанс', 'Закрывайте кассовые разрывы и получайте поддержку под поездки.', 'from-[#4B1D8B] to-[#B7FF2A]', 'Поддержка'], ['Catalon Страхование', 'Защищайте грузы, транспорт и ответственность участников сделки.', 'from-[#2F7DFF] to-[#20D6FF]', 'Защита'], ['Catalon Лизинг', 'Расширяйте автопарк и обновляйте транспорт под реальные задачи.', 'from-[#4B1D8B] to-[#FF8A00]', 'Экономия'], ['Catalon Шины, запчасти и масла', 'Закупайте расходники и комплектующие для транспорта.', 'from-[#19151F] to-[#B7FF2A]', 'Сервис'], ['Catalon Торговый дом', 'Получайте доступ к B2B-закупкам и партнёрским предложениям.', 'from-[#FF5BAA] to-[#FF8A00]', 'Партнёрство'], ['Catalon Автосервис', 'Обслуживайте транспорт через партнёрскую сервисную сеть.', 'from-[#FF8A00] to-[#FF3B30]', 'Сервис'], ['Юридический сервис', 'Договоры, претензии, споры и сопровождение сделок.', 'from-[#241047] to-[#2F7DFF]', 'Поддержка']]; return <section data-block-id="road-services-catalog" data-block-title="Экосистема сервисов Catalon" className="mx-auto max-w-[1440px] px-4 py-20 sm:px-6 lg:px-10 lg:py-28"><div className="mb-10 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#7133D0]">Экосистема сервисов</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-0.04em] sm:text-5xl">Экосистема сервисов Catalon</h2><p className="mt-5 leading-7 text-[#675F6F]">Подключайте сервисы для снижения затрат, поддержки рейса и обслуживания транспорта в одном цифровом пространстве.</p></div><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([title, description, gradient, badge]) => <div key={title}><ServiceCard title={title} description={description} gradient={gradient} badge={badge} /></div>)}</div></section>; }
