import { ArrowRight, Check, FileText, Gauge, Handshake, Map, ShieldCheck, Truck, WalletCards } from 'lucide-react';
import { ServiceCard } from './components/ServiceCard';
import safeDealImage from '../assets/1/Безопасная сделка.png';
import financeImage from '../assets/1/Финансирование под конкретный рейс.png';
import servicesImage from '../assets/1/Сервисы.png';
import portalImage from '../assets/1/Вся операционная работа в одной системе.png';

const base = import.meta.env.BASE_URL.replace(/\/$/, '');

function Header() {
  return <header className="sticky top-0 z-50 bg-[#440D84] text-white shadow-lg"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><a href={`${base}/v2`} className="text-xl font-black tracking-tight">CATALON<span className="text-[#B7FF2A]">.</span></a><nav className="hidden gap-7 text-sm font-semibold lg:flex"><a href="#audiences">Для кого</a><a href="#solutions">Решения</a><a href="#portal">Портал</a><a href="#partners">Партнёры</a></nav><a href="#start" className="rounded-full bg-[#B7FF2A] px-5 py-2.5 text-sm font-bold text-[#350375]">Обсудить задачу</a></div></header>;
}

const cards = [
  ['Заказчикам', 'Организовать перевозку', 'Подберите автомобильный или мультимодальный маршрут, рассчитайте тариф, оформите заявку и контролируйте груз в личном кабинете.', 'Выбрать перевозку', '#solutions'],
  ['Перевозчикам', 'Зарабатывать и экономить', 'Получайте доступ к подходящим грузам, безопасным сделкам, финансированию и сервисам для снижения затрат.', 'Для перевозчика', '#carrier'],
  ['Экспедиторам', 'Управлять цепочкой', 'Собирайте предложения, подключайте участников, контролируйте документы и развивайте партнёрскую модель работы.', 'Для экспедитора', '#forwarders'],
];

export default function LandingPageV2() {
  return <div className="min-h-screen bg-[#FAF8FC] text-[#19131F]"><Header /><main>
    <section className="relative overflow-hidden bg-[radial-gradient(circle_at_80%_20%,rgba(183,255,42,.22),transparent_28%),linear-gradient(135deg,#440D84,#2D075A)] px-5 py-20 text-white lg:py-28"><div className="pointer-events-none absolute -bottom-32 -left-20 h-80 w-80 rounded-full bg-[#7133D0]/50 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Цифровые решения для грузоперевозок</p><h1 className="mt-5 text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">Перевозка груза и работа перевозчика — в одном цифровом контуре</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">CATALON соединяет заказчиков, перевозчиков и экспедиторов: от расчёта тарифа и заявки до контроля маршрута и закрывающих документов.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#audiences" className="rounded-full bg-[#B7FF2A] px-6 py-3.5 font-bold text-[#350375] shadow-[0_12px_35px_rgba(183,255,42,.2)]">Выбрать сценарий <ArrowRight className="ml-2 inline h-4 w-4" /></a><a href="#solutions" className="rounded-full border border-white/30 bg-white/5 px-6 py-3.5 font-bold backdrop-blur">Посмотреть решения</a></div></div><div className="relative rounded-[34px] border border-white/15 bg-white/10 p-4 shadow-[0_25px_80px_rgba(0,0,0,.25)] backdrop-blur sm:p-6"><div className="mb-4 flex items-center justify-between text-xs text-white/60"><span>CATALON workspace</span><span className="rounded-full bg-[#B7FF2A]/20 px-3 py-1 text-[#B7FF2A]">online</span></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5 text-[#350375] shadow-xl"><Truck className="h-7 w-7" /><p className="mt-8 font-bold">Маркетплейс решений</p><p className="mt-2 text-sm text-[#675F6F]">Для грузоотправителей и клиентов</p></div><div className="rounded-2xl bg-[#B7FF2A] p-5 text-[#350375] shadow-xl"><WalletCards className="h-7 w-7" /><p className="mt-8 font-bold">Экосистема</p><p className="mt-2 text-sm">Для перевозчиков и партнёров</p></div></div><div className="mt-3 h-24 rounded-2xl bg-gradient-to-r from-white/10 to-[#B7FF2A]/20 p-4"><div className="h-2 w-2/3 rounded-full bg-[#B7FF2A]" /><div className="mt-3 h-2 w-1/2 rounded-full bg-white/25" /><div className="mt-3 h-2 w-3/4 rounded-full bg-white/15" /></div></div></div></section>
    <section id="audiences" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Выберите сценарий</p><h2 className="mt-3 text-4xl font-black tracking-tight">Один рынок — разные задачи</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{cards.map(([eyebrow,title,text,cta,href]) => <article key={title} className="rounded-[28px] bg-white p-8 shadow-sm ring-1 ring-[#E7DFEF]"><p className="text-sm font-bold text-[#7133D0]">{eyebrow}</p><h3 className="mt-3 text-3xl font-black">{title}</h3><p className="mt-4 max-w-xl leading-7 text-[#675F6F]">{text}</p><a href={href} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#440D84] px-5 py-3 text-sm font-bold text-white">{cta}<ArrowRight className="h-4 w-4" /></a></article>)}</div></section>
    <section id="solutions" className="bg-[#F1E8FA] px-5 py-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Для заказчиков</p><h2 className="mt-3 text-4xl font-black tracking-tight">Организуйте перевозку под задачу</h2><div className="mt-10 grid gap-5 lg:grid-cols-2"><a href={`${base}/v2/road-freight-russia`} className="rounded-[28px] bg-white p-7"><Truck className="h-7 w-7 text-[#7133D0]" /><h3 className="mt-6 text-2xl font-black">Автомобильные перевозки по России</h3><p className="mt-3 leading-7 text-[#675F6F]">FTL и LTL, разовые и регулярные рейсы, подбор транспорта и документы онлайн.</p><span className="mt-6 inline-flex items-center gap-2 font-bold text-[#440D84]">Подробнее <ArrowRight className="h-4 w-4" /></span></a><a href={`${base}/v2/multimodal-container`} className="rounded-[28px] bg-[#440D84] p-7 text-white"><Map className="h-7 w-7 text-[#B7FF2A]" /><h3 className="mt-6 text-2xl font-black">Мультимодальные и контейнерные перевозки</h3><p className="mt-3 leading-7 text-white/70">Автомобильные, железнодорожные, морские и терминальные этапы в одном управляемом маршруте.</p><span className="mt-6 inline-flex items-center gap-2 font-bold text-[#B7FF2A]">Подробнее <ArrowRight className="h-4 w-4" /></span></a></div></div></section>
    <section id="catalog" className="mx-auto max-w-7xl rounded-[36px] bg-[#F2F2F0] px-5 py-20 lg:px-8"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Каталог решений</p><h2 className="mt-3 text-4xl font-black tracking-tight">Решения CATALON для разных задач</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-[#675F6F]">Выбирайте готовый сценарий перевозки или соберите собственную схему вместе с командой CATALON.</p></div><div className="mt-10 grid gap-6 md:grid-cols-3">{[[Truck,'Автомобильные перевозки','FTL и LTL по России','/v2/road-freight-russia'],[Map,'Мультимодальные перевозки','Контейнеры, порты и переходы','/v2/multimodal-container'],[Gauge,'Собрать решение','Подберём маршрут и формат под вашу задачу','#start']].map(([Icon,title,text,href],index)=>{const I=Icon as typeof Truck;return <a key={title as string} href={`${href as string}`.startsWith('/')?`${base}${href as string}`:href as string} className={`group overflow-hidden rounded-[32px] border-2 ${index===1?'border-[#7133D0]':'border-[#B7FF2A]'} bg-white p-8 shadow-sm transition hover:-translate-y-2 hover:shadow-2xl`}><div className="flex items-center justify-between"><I className="h-7 w-7 text-[#4B1D8B]" /><span className="rounded-full bg-[#F2F2F0] px-3 py-1 text-xs font-bold text-[#675F6F]">Активное решение</span></div><h3 className="mt-12 text-2xl font-black">{title as string}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-[#675F6F]">{text as string}</p><div className="mt-7 flex h-24 items-end justify-between rounded-2xl bg-[#F2F2F0] p-4"><div className="h-2 w-2/3 rounded-full bg-[#D5D1DB]" /><ArrowRight className="h-5 w-5 text-[#4B1D8B] transition group-hover:translate-x-1" /></div><span className="mt-7 inline-flex rounded-full bg-[#241047] px-6 py-3 text-sm font-bold text-white">Подробнее</span></a>})}</div></section>
    <section id="portal" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Личный кабинет CATALON</p><h2 className="mt-3 text-4xl font-black">Вся перевозка — в одном окне</h2><p className="mt-5 leading-7 text-[#675F6F]">Оформляйте заявки, получайте мгновенный расчёт тарифа, отслеживайте груз и забирайте транспортные и закрывающие документы 24/7.</p></div><div className="grid gap-3 sm:grid-cols-2">{[['Расчёт тарифа', Gauge], ['Заявки онлайн', FileText], ['Контроль груза', Map], ['Документы 24/7', Check]].map(([label, Icon]) => { const I = Icon as typeof Check; return <div key={label as string} className="rounded-2xl bg-white p-5 ring-1 ring-[#E7DFEF]"><I className="h-5 w-5 text-[#7133D0]" /><p className="mt-5 font-bold">{label as string}</p></div>; })}</div></div></section>
    <section id="platform-services" className="mx-auto max-w-7xl rounded-[36px] bg-[#440D84] px-5 py-20 text-white"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Каталог сервисов</p><h2 className="mt-3 text-4xl font-black">Сервисы экосистемы для перевозчиков</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-white/65">Дополнительные инструменты подключаются к задаче перевозчика и помогают снижать операционные расходы.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3"><ServiceCard title="Топливо" description="Партнёрские условия и меньше затрат на рейс." gradient="from-[#7133D0] to-[#350375]" badge="Экономия" /><ServiceCard title="Страхование" description="Дополнительная защита груза и ответственности." gradient="from-[#2F7DFF] to-[#440D84]" badge="Защита" /><ServiceCard title="Сервис и право" description="Автосервис, запчасти, юридическая поддержка и операционная помощь." gradient="from-[#6CAA00] to-[#2E6B14]" badge="Поддержка" /></div><div className="mt-8 overflow-hidden rounded-[28px] bg-white/10 p-3"><img src={servicesImage} alt="Каталог сервисов CATALON" className="h-48 w-full rounded-[22px] object-cover object-center opacity-90" /></div></section>
    <section id="workflow" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Как работает CATALON</p><h2 className="mt-3 text-4xl font-black">От задачи до результата — в одном процессе</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-[#675F6F]">Заказчик, перевозчик и экспедитор работают в своих сценариях, а заявка сохраняет общий контекст сделки.</p></div><ol className="mt-10 grid gap-4 md:grid-cols-4">{[['01','Заявка','Опишите груз, маршрут или свободный транспорт.'],['02','Подбор решения','CATALON соединяет задачу с подходящим сценарием.'],['03','Сделка','Условия, участники и этапы фиксируются в системе.'],['04','Результат','Статусы, документы и закрытие доступны онлайн.']].map(([num,title,text])=><li key={num} className="rounded-[26px] border border-[#E7DFEF] bg-white p-6 shadow-sm"><span className="text-3xl font-black text-[#7133D0]">{num}</span><h3 className="mt-7 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#675F6F]">{text}</p></li>)}</ol></section>
    <section id="trust" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 lg:grid-cols-2"><article className="overflow-hidden rounded-[30px] bg-[#440D84] text-white shadow-xl"><div className="grid gap-6 p-7 lg:grid-cols-[1fr_.8fr] lg:p-10"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Защита интересов сторон</p><h2 className="mt-4 text-3xl font-black">Безопасная сделка</h2><p className="mt-4 text-sm leading-6 text-white/65">Проверяем участников, фиксируем условия и связываем заявку, этапы и документы в одной сделке.</p></div><img src={safeDealImage} alt="Безопасная сделка CATALON" className="h-40 w-full rounded-2xl object-cover" /></div></article><article className="overflow-hidden rounded-[30px] bg-[#DCC8F5] shadow-xl"><div className="grid gap-6 p-7 lg:grid-cols-[1fr_.8fr] lg:p-10"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#440D84]">Оборотные средства</p><h2 className="mt-4 text-3xl font-black text-[#350375]">Финансирование под рейс</h2><p className="mt-4 text-sm leading-6 text-[#4D3C5D]">Финансовый инструмент привязан к параметрам подтверждённой перевозки и её документам.</p></div><img src={financeImage} alt="Финансирование под конкретный рейс" className="h-40 w-full rounded-2xl object-cover" /></div></article></div></section>
    <section id="carrier" className="bg-[#180527] px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Для перевозчиков</p><h2 className="mt-3 text-4xl font-black">Больше загрузок. Меньше затрат.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Зарабатывать', 'Подходящие грузы и меньше холостого пробега', Truck], ['Безопасная сделка', 'Проверенные контрагенты и прозрачные условия', ShieldCheck], ['Финансирование', 'Поддержка исполнения подтверждённого рейса', WalletCards], ['Сервисы', 'Топливо, страхование, ремонт и юридическая помощь', Handshake]].map(([title,text,Icon]) => { const I = Icon as typeof Truck; return <article key={title as string} className="rounded-2xl bg-white/10 p-5"><I className="h-6 w-6 text-[#B7FF2A]" /><h3 className="mt-6 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-white/60">{text as string}</p></article>; })}</div></div></section>
    <section id="forwarders" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="rounded-[30px] bg-white p-8 ring-1 ring-[#E7DFEF] lg:p-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Для экспедиторов</p><h2 className="mt-3 text-4xl font-black">Цифровая модель управления перевозками</h2><p className="mt-5 max-w-2xl leading-7 text-[#675F6F]">Подбирайте транспорт под заявки заказчиков, подключайте партнёров, управляйте документами и получайте аналитику по сделкам в одной системе.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{['Подбор транспорта', 'Партнёрская модель', 'BI-аналитика'].map(x => <div key={x} className="rounded-xl bg-[#F1E8FA] p-4 font-bold">{x}</div>)}</div></div></section>
    <section id="partners" className="mx-auto max-w-7xl px-5 py-16 text-center lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Партнёры CATALON</p><h2 className="mt-3 text-3xl font-black">Соединяем технологии и логистическую инфраструктуру</h2><p className="mx-auto mt-4 max-w-2xl text-[#675F6F]">FESCO, «ТрансКонтейнер» и сервисные партнёры помогают формировать решения для разных маршрутов и задач.</p></section>
    <section id="start" className="px-5 pb-6"><div className="mx-auto max-w-7xl rounded-[30px] bg-[#B7FF2A] px-6 py-14 text-center text-[#350375]"><h2 className="text-4xl font-black">Начните с вашей задачи</h2><p className="mx-auto mt-4 max-w-xl">Расскажите, что нужно перевезти или какой рейс вы хотите найти.</p><a href="mailto:info@catalon.ru" className="mt-7 inline-block rounded-full bg-[#440D84] px-6 py-3.5 font-bold text-white">Связаться с CATALON</a></div></section>
  </main></div>;
}
