import { ArrowRight, Check, FileArchive, FileText, Map, Ship, TrainFront, Truck, Warehouse } from 'lucide-react';
import multimodalImage from '../assets/1/Мультимодальные и контейнерные перевозки.png';

const base = import.meta.env.BASE_URL.replace(/\/$/, '');
const stages = [['Заявка', FileText], ['Расчёт тарифа', Map], ['Сборка маршрута', Warehouse], ['Согласование', Check], ['Отправка', Truck], ['Контроль перемещения', Ship], ['Документы', FileArchive], ['Закрытие', Check]];

function Header() { return <header className="sticky top-0 z-50 bg-[#440D84] text-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><a href={`${base}/v2`} className="text-xl font-black">CATALON<span className="text-[#B7FF2A]">.</span></a><nav className="hidden gap-7 text-sm font-bold lg:flex"><a href="#route">Маршрут</a><a href="#cargo">Грузы</a><a href="#geography">География</a><a href="#cabinet">Кабинет</a></nav><a href="#start" className="rounded-full bg-[#B7FF2A] px-5 py-2.5 text-sm font-bold text-[#350375]">Собрать маршрут</a></div></header>; }

export default function MultimodalPageV2() { return <div className="min-h-screen bg-[#FAF8FC] text-[#19131F]"><Header /><main>
  <section className="relative overflow-hidden bg-[radial-gradient(circle_at_85%_20%,rgba(183,255,42,.2),transparent_24%),linear-gradient(135deg,#440D84,#2B0755)] px-5 py-20 text-white lg:py-28"><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Самостоятельное мультимодальное решение</p><h1 className="mt-5 text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">Несколько видов транспорта — один управляемый маршрут</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">CATALON организует контейнерные перевозки с автомобильными, железнодорожными, морскими и терминальными этапами в едином цифровом процессе.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#start" className="rounded-full bg-[#B7FF2A] px-6 py-3.5 font-bold text-[#350375] shadow-[0_14px_35px_rgba(183,255,42,.18)]">Создать заявку <ArrowRight className="ml-2 inline h-4 w-4" /></a><a href="#route" className="rounded-full border border-white/30 bg-white/5 px-6 py-3.5 font-bold">Посмотреть этапы</a></div></div><div className="rounded-[30px] border border-white/15 bg-white/10 p-3 shadow-[0_25px_70px_rgba(0,0,0,.25)] backdrop-blur"><img src={multimodalImage} alt="Мультимодальные и контейнерные перевозки" className="h-64 w-full rounded-[24px] object-cover" /><div className="grid grid-cols-3 gap-2 p-3 text-center text-xs font-bold"><span className="rounded-xl bg-white/10 p-3"><TrainFront className="mx-auto mb-2 text-[#B7FF2A]" />ЖД</span><span className="rounded-xl bg-white/10 p-3"><Ship className="mx-auto mb-2 text-[#B7FF2A]" />Море</span><span className="rounded-xl bg-white/10 p-3"><Truck className="mx-auto mb-2 text-[#B7FF2A]" />Доставка</span></div></div></div></section>
  <section id="route" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Единый процесс</p><h2 className="mt-3 text-4xl font-black">Маршрут от заявки до закрытия</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stages.map(([title,Icon], i) => { const I = Icon as typeof Check; return <div key={title as string} className="rounded-2xl bg-white p-5 ring-1 ring-[#E7DFEF]"><span className="text-sm font-black text-[#7133D0]">0{i + 1}</span><I className="mt-6 h-6 w-6 text-[#7133D0]" /><h3 className="mt-5 font-bold">{title as string}</h3></div>; })}</div></section>
  <section id="cargo" className="bg-[#F1E8FA] px-5 py-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Что перевозим</p><h2 className="mt-3 text-4xl font-black">Решения для разных типов груза</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{['Универсальные контейнеры', 'Рефрижераторные контейнеры', 'Генеральные грузы', 'Опасные грузы'].map(x => <article key={x} className="rounded-2xl bg-white p-6"><Check className="h-6 w-6 text-[#7133D0]" /><h3 className="mt-6 font-bold">{x}</h3><p className="mt-2 text-sm leading-6 text-[#675F6F]">Подбор схемы перевозки и контроль этапов в едином маршруте.</p></article>)}</div></div></section>
  <section id="geography" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">География отправок</p><h2 className="mt-3 text-4xl font-black">Порты и сухопутные переходы</h2><p className="mt-5 leading-7 text-[#675F6F]">CATALON помогает строить маршруты через доступные транспортные узлы. Конкретная схема и условия подтверждаются при расчёте заявки.</p></div><div className="grid gap-3 sm:grid-cols-2">{['Владивосток и Восточный', 'Санкт-Петербург', 'Новороссийск', 'Забайкальск', 'Достык', 'Алтынколь', 'Наушки', 'Другие порты и переходы'].map(x => <div key={x} className="flex items-center gap-3 rounded-xl bg-white p-4 font-bold ring-1 ring-[#E7DFEF]"><Map className="h-5 w-5 shrink-0 text-[#7133D0]" />{x}</div>)}</div></div></section>
  <section id="cabinet" className="bg-[#180527] px-5 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Личный кабинет 24/7</p><h2 className="mt-3 text-4xl font-black">Груз, этапы и документы в одном окне</h2><p className="mt-5 leading-7 text-white/65">Получайте информацию о перевозке, отслеживайте местонахождение груза и даты отгрузки, работайте с транспортными и закрывающими документами.</p></div><div className="grid gap-3 sm:grid-cols-2">{['Мгновенный расчёт тарифа', 'Оформление заявки', 'Статусы и местонахождение', 'Электронный документооборот'].map(x => <div key={x} className="rounded-2xl bg-white/10 p-5 font-bold"><Check className="mb-5 text-[#B7FF2A]" />{x}</div>)}</div></div></section>
  <section id="start" className="px-5 py-6"><div className="mx-auto max-w-7xl rounded-[30px] bg-[#B7FF2A] px-6 py-14 text-center text-[#350375]"><h2 className="text-4xl font-black">Соберите мультимодальный маршрут</h2><p className="mx-auto mt-4 max-w-xl">Опишите груз и направление — команда CATALON поможет рассчитать схему перевозки.</p><a href="mailto:info@catalon.ru" className="mt-7 inline-block rounded-full bg-[#440D84] px-6 py-3.5 font-bold text-white">Обсудить маршрут</a></div></section>
  </main></div>; }
