import { ArrowRight, Check, FileText, Gauge, ShieldCheck, Truck, WalletCards } from 'lucide-react';
import portalImage from '../assets/1/Перевозка под контролем, а не в переписках.png';
import safeDealImage from '../assets/1/Безопасная сделка.png';
import financeImage from '../assets/1/Финансирование под конкретный рейс.png';

const base = import.meta.env.BASE_URL.replace(/\/$/, '');
const steps = [['01', 'Оформите заявку', 'Укажите маршрут, груз и желаемые условия.'], ['02', 'Подберём транспорт', 'Получите подходящие предложения перевозчиков.'], ['03', 'Согласуйте условия', 'Зафиксируйте стоимость, сроки и участников.'], ['04', 'Контролируйте рейс', 'Видите статус перевозки и документы онлайн.'], ['05', 'Закройте перевозку', 'Получите закрывающие документы в кабинете.']];

function Header() { return <header className="sticky top-0 z-50 bg-[#B7FF2A] text-[#350375]"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><a href={`${base}/v2`} className="text-xl font-black">CATALON<span className="text-[#7133D0]">.</span></a><nav className="hidden gap-7 text-sm font-bold lg:flex"><a href="#process">Как работает</a><a href="#features">Возможности</a><a href="#carriers">Перевозчикам</a><a href={`${base}/v2/multimodal-container`}>Мультимодал</a></nav><a href="#start" className="rounded-full bg-[#440D84] px-5 py-2.5 text-sm font-bold text-white">Начать заявку</a></div></header>; }

export default function RoadFreightPageV2() { return <div className="min-h-screen bg-[#FAF8FC] text-[#19131F]"><Header /><main>
  <section className="relative overflow-hidden bg-[linear-gradient(120deg,#B7FF2A,#D9FF8A_55%,#A7E94A)] px-5 py-20 lg:py-28"><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Решение для заказчиков</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">Автомобильные перевозки по России — от заявки до документов</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#4D3C5D]">FTL и LTL-перевозки, подбор транспорта, расчёт стоимости и контроль рейса через единый цифровой портал CATALON.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#start" className="rounded-full bg-[#440D84] px-6 py-3.5 font-bold text-white shadow-[0_14px_35px_rgba(68,13,132,.2)]">Оформить заявку <ArrowRight className="ml-2 inline h-4 w-4" /></a><a href="#process" className="rounded-full border border-[#440D84]/30 bg-white/30 px-6 py-3.5 font-bold text-[#440D84]">Как это работает</a></div><div className="mt-8 flex flex-wrap gap-2 text-sm font-bold">{['FTL', 'LTL', 'Разовые рейсы', 'Регулярные поставки', 'Контрактные перевозки'].map(x => <span key={x} className="rounded-full bg-white/60 px-3 py-2 shadow-sm">{x}</span>)}</div></div><div className="rounded-[30px] bg-white/50 p-3 shadow-[0_25px_70px_rgba(68,13,132,.18)] backdrop-blur"><img src={portalImage} alt="Перевозка под контролем в CATALON" className="h-72 w-full rounded-[24px] object-cover object-center" /><div className="flex items-center justify-between px-3 py-4 text-sm font-bold text-[#440D84]"><span>Статус рейса</span><span className="rounded-full bg-[#B7FF2A] px-3 py-1">Под контролем</span></div></div></div></section>
  <section id="features" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Что получает заказчик</p><h2 className="mt-3 text-4xl font-black">Перевозка под контролем, а не в переписках</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Быстрый расчёт', 'Рассчитайте стоимость и оформите заявку.', Gauge], ['Подбор транспорта', 'Подходящие предложения в одном окне.', Truck], ['Безопасная сделка', 'Условия и участники зафиксированы.', ShieldCheck], ['Документы онлайн', 'Транспортные и закрывающие документы 24/7.', FileText]].map(([title,text,Icon]) => { const I = Icon as typeof Truck; return <article key={title as string} className="rounded-2xl bg-white p-6 ring-1 ring-[#E7DFEF]"><I className="h-6 w-6 text-[#7133D0]" /><h3 className="mt-6 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#675F6F]">{text as string}</p></article>; })}</div></section>
  <section id="process" className="bg-[#440D84] px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Клиентский сценарий</p><h2 className="mt-3 text-4xl font-black">От заявки до закрытого рейса</h2><ol className="mt-10 grid gap-4 md:grid-cols-5">{steps.map(([num,title,text]) => <li key={num} className="border-t border-white/20 pt-5"><span className="text-3xl font-black text-[#B7FF2A]">{num}</span><h3 className="mt-6 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/60">{text}</p></li>)}</ol></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 lg:grid-cols-2"><article className="overflow-hidden rounded-[30px] bg-[#7133D0] text-white shadow-xl"><div className="p-7 lg:p-10"><img src={safeDealImage} alt="Безопасная сделка" className="mb-7 h-40 w-full rounded-2xl object-cover" /><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Защита интересов сторон</p><h2 className="mt-3 text-3xl font-black">Безопасная сделка</h2><p className="mt-4 text-sm leading-6 text-white/70">Условия, участники и документы связаны с конкретным рейсом. Меньше неоднозначности — больше прозрачности.</p></div></article><article className="overflow-hidden rounded-[30px] bg-[#DCC8F5] shadow-xl"><div className="p-7 lg:p-10"><img src={financeImage} alt="Финансирование под конкретный рейс" className="mb-7 h-40 w-full rounded-2xl object-cover" /><p className="text-sm font-bold uppercase tracking-[.2em] text-[#440D84]">Оборотные средства</p><h2 className="mt-3 text-3xl font-black text-[#350375]">Финансирование под конкретный рейс</h2><p className="mt-4 text-sm leading-6 text-[#4D3C5D]">Финансовая заявка связана с параметрами подтверждённой перевозки и её документами.</p></div></article></div></section>
  <section id="carriers" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="rounded-[30px] bg-[#F1E8FA] p-8 lg:p-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#7133D0]">Отдельный сценарий для перевозчиков</p><h2 className="mt-3 text-4xl font-black">Зарабатывайте больше и снижайте затраты</h2><p className="mt-5 max-w-2xl leading-7 text-[#675F6F]">Получайте доступ к свободным грузам и сервисам экосистемы, не смешивая их с клиентским процессом перевозки.</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Подходящие рейсы', 'Меньше холостого пробега', 'Финансирование рейса', 'Топливо и страхование'].map(x => <div key={x} className="flex items-center gap-3 rounded-xl bg-white p-4 text-sm font-bold"><Check className="h-5 w-5 text-[#7133D0]" />{x}</div>)}</div></div></section>
  <section className="bg-[#180527] px-5 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#B7FF2A]">Личный кабинет</p><h2 className="mt-3 text-4xl font-black">Все данные по рейсу — в одном месте</h2><p className="mt-5 leading-7 text-white/65">Заявка, предложения, стоимость, статусы и документы связаны с одной перевозкой и доступны онлайн.</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-5"><FileText className="text-[#B7FF2A]" /><p className="mt-6 font-bold">Заявка и документы</p></div><div className="rounded-2xl bg-white/10 p-5"><ShieldCheck className="text-[#B7FF2A]" /><p className="mt-6 font-bold">Прозрачная сделка</p></div></div></div></section>
  <section id="start" className="px-5 py-6"><div className="mx-auto max-w-7xl rounded-[30px] bg-[#B7FF2A] px-6 py-14 text-center text-[#350375]"><h2 className="text-4xl font-black">Организуйте следующий рейс</h2><p className="mt-4">Расскажите о маршруте — команда CATALON поможет подобрать решение.</p><a href="mailto:info@catalon.ru" className="mt-7 inline-block rounded-full bg-[#440D84] px-6 py-3.5 font-bold text-white">Обсудить перевозку</a></div></section>
  </main></div>; }
